<?php
require '/tmp/fpmock/pre.php';
require '/home/claude/rcr/includes/bootstrap.php';
require_once '/home/claude/rcr/includes/payment_helpers.php';
$S='/tmp/fpmock/state.json';
$set=function(array $a) use ($S){ file_put_contents($S, json_encode(array_merge(json_decode(file_get_contents($S),true)?:[], $a))); };
$ok=0;$ko=0; $t=function($n,$c,$d='') use(&$ok,&$ko){ if($c){$ok++;echo "[OK ] $n\n";}else{$ko++;echo "[FAIL] $n $d\n";} };
$A=['status'=>'0','amount'=>1,'currency'=>'USD'];
$bdd->exec("DROP TEMPORARY TABLE IF EXISTS tmp_ad"); $bdd->exec("CREATE TEMPORARY TABLE tmp_ad SELECT * FROM adhesion LIMIT 1");
$bdd->exec("UPDATE tmp_ad SET id_ad=99001, codes='SCEN0001', mail='scen@test.invalid', statut='en_attente', date_echeance=NULL");
$bdd->exec("INSERT INTO adhesion SELECT * FROM tmp_ad");
$idAd=99001;
$new=function() use($bdd,$idAd){ $ref=payment_new_reference('A'); $ord=bin2hex(random_bytes(6)).'243812345678';
  $bdd->prepare("INSERT INTO payments (adhesion_id,id_ad,codes_ad,reference,reference_payment,telephone_py,montant,devise,currency,provider,status,type_transaction,id_cot,canal,order_number,transaction_id) VALUES (?,?,?,?,?,?,1,'USD','USD','FLEXPAY','processing','adhesion',1,'mobile_money',?,?)")->execute([$idAd,$idAd,'SCEN0001',$ref,$ref,'243812345678',$ord,$ord]);
  return [(int)$bdd->lastInsertId(),$ref,$ord]; };
$st=fn($id)=>$bdd->query("SELECT status FROM payments WHERE id=$id")->fetchColumn();
$act=fn()=>$bdd->query("SELECT statut FROM adhesion WHERE id_ad=$idAd")->fetchColumn();
$ech=fn()=>$bdd->query("SELECT date_echeance FROM adhesion WHERE id_ad=$idAd")->fetchColumn();
$npaid=fn($ref)=>(int)$bdd->query("SELECT COUNT(*) FROM payment_logs WHERE reference='$ref' AND evenement='status_change' AND statut_apres='paid'")->fetchColumn();
$cb=function($ref,$ord,$code='0'){ $c=curl_init('http://127.0.0.1:8092/api/flexpay_callback.php'); curl_setopt_array($c,[CURLOPT_POST=>1,CURLOPT_RETURNTRANSFER=>1,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>json_encode(['code'=>$code,'reference'=>$ref,'provider_reference'=>'PR123','orderNumber'=>$ord])]); $r=curl_exec($c); $h=curl_getinfo($c,CURLINFO_HTTP_CODE); return [$h,json_decode((string)$r,true)]; };
$chk=fn($id)=>payment_flexpay_check($bdd,'adhesion',$id);

[$id,$ref,$ord]=$new(); $set([$ord=>$A]); [$h,$j]=$cb($ref,$ord);
$t('1 succès immédiat via callback HTTP', $h===200 && $st($id)==='paid' && $act()==='actif', "h=$h st=".$st($id));
[$id,$ref,$ord]=$new(); $set([$ord=>['status'=>'4']+$A]);
$t('2a pending : rien ne change', $chk($id)===null && $st($id)==='processing');
$set([$ord=>$A]); $t('2b succès détecté au re-check', $chk($id)==='paid' && $st($id)==='paid');
[$id,$ref,$ord]=$new(); $set([$ord=>$A]); $chk($id); [$h,$j]=$cb($ref,$ord);
$t('3 callback tardif après finalisation : already_paid', $h===200 && ($j['result']??'')==='already_paid');
[$id,$ref,$ord]=$new(); $set([$ord=>$A]); $cb($ref,$ord); $cb($ref,$ord);
$t('4 callback x2 : une seule validation', $npaid($ref)===1);
[$id,$ref,$ord]=$new(); $set([$ord=>$A]); $chk($id);$chk($id);$e1=$ech(); $chk($id);$chk($id);
$t('5 rechargements : pas de double prolongation', $e1===$ech());
[$id,$ref,$ord]=$new(); $set([$ord=>$A]); $bdd->exec("UPDATE payments SET created_at=NOW()-INTERVAL 20 MINUTE WHERE id=$id");
$o2=[]; exec('php -d auto_prepend_file=/tmp/fpmock/pre.php /home/claude/rcr/tools/cron.php --paiements 2>&1 | tail -3',$o2);
$t('6 navigateur fermé : le cron finalise', $st($id)==='paid', implode('|',$o2));
[$id,$ref,$ord]=$new(); $set(['__mode'=>'http500',$ord=>$A]);
$t('7a HTTP 500 : aucune décision', $chk($id)===null && $st($id)==='processing');
$set(['__mode'=>'nonjson']); $t('7b réponse non JSON : aucune décision', $chk($id)===null && $st($id)==='processing');
$set(['__mode'=>'ok']); $t('7c FlexPay revient : validé', $chk($id)==='paid');
[$id,$ref,$ord]=$new(); $t('8 transaction inconnue : inchangé', $chk($id)===null && $st($id)==='processing');
[$id,$ref,$ord]=$new(); $set([$ord=>['status'=>'1']+$A]);
$t('9a échec < 3 min : attente', $chk($id)===null); $bdd->exec("UPDATE payments SET created_at=NOW()-INTERVAL 10 MINUTE WHERE id=$id");
$t('9b échec > 3 min : failed', $chk($id)==='failed' && $st($id)==='failed');
[$id1,$r1,$o1]=$new(); [$id2,$r2,$o2b]=$new(); $set([$o1=>['status'=>'1']+$A,$o2b=>$A]);
$chk($id1); $chk($id2); $t('10 deux demandes : seule la payée est validée', $st($id2)==='paid' && $st($id1)!=='paid');
[$id,$ref,$ord]=$new(); $set([$ord=>['status'=>'1']+$A]); $cb($ref,$ord,'0');
$t('S1 faux callback code 0 : rien validé', $st($id)!=='paid');
[$h,$j]=$cb('RCR-A-000000-FFFFFFFFFF','ZZZZZZZZZZZZ'); $t('S2 référence inconnue : 404', $h===404);
[$id,$ref,$ord]=$new(); $set([$ord=>['amount'=>0.5]+$A]); $chk($id); $t('S3 montant différent : refusé', $st($id)!=='paid');
[$id,$ref,$ord]=$new(); $set([$ord=>$A]);
$ps=[]; for($i=0;$i<4;$i++){ $ps[]=popen("php /tmp/fpmock/one.php $id",'r'); } foreach($ps as $p){pclose($p);}
$t('C1 4 processus simultanés : une seule finalisation', $npaid($ref)===1 && $st($id)==='paid', 'n='.$npaid($ref));
$bdd->exec("DELETE FROM payment_logs WHERE reference IN (SELECT reference FROM payments WHERE id_ad=$idAd)"); $bdd->exec("DELETE FROM payments WHERE id_ad=$idAd"); $bdd->exec("DELETE FROM notifications WHERE id_ad=$idAd"); $bdd->exec("DELETE FROM adhesion WHERE id_ad=$idAd");
echo "\nRÉSULTAT: $ok OK, $ko échecs\n";
